//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFHelper.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenLabel {
            get {
                object obj = ResourceManager.GetObject("GreenLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having problems with starting Tomcat.
        /// </summary>
        internal static string MainForm_tomcat_start_Having_problems_with_starting_Tomcat {
            get {
                return ResourceManager.GetString("MainForm_tomcat_start_Having_problems_with_starting_Tomcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having problems with stopping Tomcat.
        /// </summary>
        internal static string MainForm_tomcat_stop_Having_problems_with_stopping_Tomcat {
            get {
                return ResourceManager.GetString("MainForm_tomcat_stop_Having_problems_with_stopping_Tomcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedLabel {
            get {
                object obj = ResourceManager.GetObject("RedLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Settings_Relocate_Directories {
            get {
                return ResourceManager.GetString("Settings_Relocate_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is used by another application.
        /// </summary>
        internal static string TestFileImport_button1_Click_File_is_used_by_another_application {
            get {
                return ResourceManager.GetString("TestFileImport_button1_Click_File_is_used_by_another_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        internal static string TestFileImport_button2_Click_Are_you_sure__ {
            get {
                return ResourceManager.GetString("TestFileImport_button2_Click_Are_you_sure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened !!!.
        /// </summary>
        internal static string TestFileImport_button2_Click_Something_happened____ {
            get {
                return ResourceManager.GetString("TestFileImport_button2_Click_Something_happened____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update confirmation.
        /// </summary>
        internal static string TestFileImport_button2_Click_Update_confirmation {
            get {
                return ResourceManager.GetString("TestFileImport_button2_Click_Update_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string TestFileImport_button3_Click_Delete_confirmation {
            get {
                return ResourceManager.GetString("TestFileImport_button3_Click_Delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not exists.
        /// </summary>
        internal static string TestFileImport_button3_Click_File_is_not_exists {
            get {
                return ResourceManager.GetString("TestFileImport_button3_Click_File_is_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file, it is may be used by another process.
        /// </summary>
        internal static string TestFileImport_button3_Click_Unable_to_delete_file__it_is_may_be_used_by_another_process {
            get {
                return ResourceManager.GetString("TestFileImport_button3_Click_Unable_to_delete_file__it_is_may_be_used_by_another_" +
                        "process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Files Folder is not exists.
        /// </summary>
        internal static string TestFileImport_comboBox1_TextChanged_Test_Files_Folder_is_not_exists {
            get {
                return ResourceManager.GetString("TestFileImport_comboBox1_TextChanged_Test_Files_Folder_is_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test files directory is not found.
        /// </summary>
        internal static string TestFileImport_FillRichTexBoxFromFile_Test_files_directory_is_not_found {
            get {
                return ResourceManager.GetString("TestFileImport_FillRichTexBoxFromFile_Test_files_directory_is_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Imported without Errors.
        /// </summary>
        internal static string TestFileImport_ShowImportLogs_File_Imported_without_Errors {
            get {
                return ResourceManager.GetString("TestFileImport_ShowImportLogs_File_Imported_without_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log folder didn&apos;t contains any files .
        /// </summary>
        internal static string TestFileImport_ShowImportLogs_Log_folder_didn_t_contains_any_files_ {
            get {
                return ResourceManager.GetString("TestFileImport_ShowImportLogs_Log_folder_didn_t_contains_any_files_", resourceCulture);
            }
        }
    }
}
